// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	"webchat_be/biz/handler"
	"webchat_be/biz/middleware"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	apiV1 := r.Group("/api/v1")
	{
		apiV1.GET("/ping", handler.Ping)

		account := apiV1.Group("/account")
		{

			account.POST("/login", []app.HandlerFunc{
				middleware.LoginLimiter(),
				handler.Login,
			}...)
			account.POST("/forget_password", handler.ForgetPassword)
			account.POST("/reset_password", handler.ResetPassword)
			account.POST("/register", handler.Register)
			account.POST("/register_verify", handler.RegisterVerify)

			loginAccount := account.Group("/", middleware.LoginStateVerify()...)
			{
				loginAccount.GET("/info", handler.GetAccountInfo)
				loginAccount.POST("/logout", handler.Logout)
				loginAccount.POST("/update_password", handler.UpdatePassword)
			}
		}

		model := apiV1.Group("/model", middleware.LoginStateVerify()...)
		{
			model.GET("/list", handler.GetModels)
		}

		chat := apiV1.Group("/chat", middleware.LoginStateVerify()...)
		{
			chat.POST("/stream",
				[]app.HandlerFunc{
					middleware.ChatLimiter(),
					handler.StreamingChat,
				}...)
		}
	}
}
