// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	handler "webchat_be/biz/handler"
	"webchat_be/biz/middleware"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	apiV1 := r.Group("/api/v1")
	{
		apiV1.GET("/ping", handler.Ping)
		account := apiV1.Group("/account")
		{
			account.POST("/login", handler.Login)
			account.POST("/forget_password", handler.ForgetPassword)
			account.POST("/reset_password", handler.ResetPassword)
			account.POST("/register", handler.Register)
			account.POST("/register_verify", handler.RegisterVerify)

			loginAccount := account.Group("/", middleware.LoginStateVerify()...)
			{
				loginAccount.GET("/models", handler.GetModels)
				loginAccount.GET("/info", handler.GetAccountInfo)
				loginAccount.POST("/logout", handler.Logout)
				loginAccount.POST("/update_password", handler.UpdatePassword)
			}

		}
	}
}
