// Code generated by hertz generator.

package handler

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Ping 测试 handler
//
//	@Summary		测试 Summary
//	@Description	测试 Description
//	@Accept			application/json
//	@Produce		application/json
//	@Router			/api/v1/ping [GET]
func Ping(ctx context.Context, c *app.RequestContext) {
	c.JSON(consts.StatusOK, utils.H{
		"message": "pong",
	})
}
