basePath: /
definitions:
  dto.AccountInfoQueryResp:
    properties:
      account_id:
        type: string
      email:
        type: string
      status:
        type: string
      username:
        type: string
    type: object
  dto.ChatCreateReq:
    properties:
      messages:
        items:
          $ref: '#/definitions/dto.Message'
        maxItems: 20
        type: array
      model_id:
        type: string
    required:
    - messages
    - model_id
    type: object
  dto.CommonResp:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
      success:
        type: boolean
    type: object
  dto.ForgetPasswordReq:
    properties:
      username:
        maxLength: 64
        type: string
    required:
    - username
    type: object
  dto.ForgetPasswordResp:
    type: object
  dto.LoginReq:
    properties:
      password:
        maxLength: 128
        type: string
      username:
        maxLength: 64
        type: string
    required:
    - password
    - username
    type: object
  dto.LoginResp:
    properties:
      account_id:
        type: string
      email:
        type: string
      status:
        type: string
      username:
        type: string
    type: object
  dto.LogoutReq:
    type: object
  dto.LogoutResp:
    type: object
  dto.Message:
    properties:
      content:
        type: string
      role:
        $ref: '#/definitions/dto.Role'
    required:
    - content
    - role
    type: object
  dto.Model:
    properties:
      model_id:
        type: string
      model_name:
        type: string
    type: object
  dto.ModelQueryResp:
    properties:
      models:
        items:
          $ref: '#/definitions/dto.Model'
        type: array
    type: object
  dto.PasswordUpdateReq:
    properties:
      password:
        maxLength: 128
        type: string
      password_new:
        maxLength: 128
        minLength: 8
        type: string
    required:
    - password
    - password_new
    type: object
  dto.PasswordUpdateResp:
    type: object
  dto.RegisterReq:
    properties:
      email:
        maxLength: 64
        type: string
      password:
        maxLength: 128
        type: string
      username:
        maxLength: 64
        type: string
    required:
    - email
    - password
    - username
    type: object
  dto.RegisterResp:
    type: object
  dto.RegisterVerifyReq:
    properties:
      email:
        maxLength: 64
        type: string
      verify_code:
        maxLength: 10
        type: string
    required:
    - email
    - verify_code
    type: object
  dto.RegisterVerifyResp:
    type: object
  dto.ResetPasswordReq:
    properties:
      password:
        maxLength: 128
        type: string
      verify_code:
        maxLength: 10
        type: string
    required:
    - password
    - verify_code
    type: object
  dto.ResetPasswordResp:
    type: object
  dto.Role:
    enum:
    - system
    - user
    - assistant
    type: string
    x-enum-varnames:
    - RoleSystem
    - RoleUser
    - RoleAssistant
info:
  contact:
    name: hertz-contrib
    url: https://github.com/hertz-contrib
  description: This is a demo using Hertz.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: HertzTest
  version: "1.0"
paths:
  /api/v1/account/forget_password:
    post:
      consumes:
      - application/json
      description: 用户忘记密码接口，请求获取验证码进行重置
      parameters:
      - description: password forget request body
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/dto.ForgetPasswordReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            set-cookie:
              description: cookie
              type: string
          schema:
            allOf:
            - $ref: '#/definitions/dto.CommonResp'
            - properties:
                data:
                  $ref: '#/definitions/dto.ForgetPasswordResp'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.CommonResp'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.CommonResp'
      summary: 用户忘记密码接口
      tags:
      - account
  /api/v1/account/info:
    get:
      consumes:
      - application/json
      description: 用户信息查询接口
      parameters:
      - description: csrf token
        in: header
        name: X-CSRF-TOKEN
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            set-cookie:
              description: cookie
              type: string
          schema:
            allOf:
            - $ref: '#/definitions/dto.CommonResp'
            - properties:
                data:
                  $ref: '#/definitions/dto.AccountInfoQueryResp'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.CommonResp'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.CommonResp'
      summary: 用户信息查询接口
      tags:
      - account
  /api/v1/account/login:
    post:
      consumes:
      - application/json
      description: 用户登录接口
      parameters:
      - description: login request body
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/dto.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            X-CSRF-TOKEN:
              description: csrf token
              type: string
            set-cookie:
              description: cookie
              type: string
          schema:
            allOf:
            - $ref: '#/definitions/dto.CommonResp'
            - properties:
                data:
                  $ref: '#/definitions/dto.LoginResp'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.CommonResp'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.CommonResp'
      summary: 用户登录接口
      tags:
      - account
  /api/v1/account/logout:
    post:
      consumes:
      - application/json
      description: 用户登出接口
      parameters:
      - description: logout request body
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/dto.LogoutReq'
      - description: csrf token
        in: header
        name: X-CSRF-TOKEN
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            set-cookie:
              description: cookie
              type: string
          schema:
            allOf:
            - $ref: '#/definitions/dto.CommonResp'
            - properties:
                data:
                  $ref: '#/definitions/dto.LogoutResp'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.CommonResp'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.CommonResp'
      summary: 用户登出接口
      tags:
      - account
  /api/v1/account/register:
    post:
      consumes:
      - application/json
      description: 用户注册接口，请求后获取验证码，然后才能创建
      parameters:
      - description: register request body
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            set-cookie:
              description: cookie
              type: string
          schema:
            allOf:
            - $ref: '#/definitions/dto.CommonResp'
            - properties:
                data:
                  $ref: '#/definitions/dto.RegisterResp'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.CommonResp'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.CommonResp'
      summary: 用户注册接口
      tags:
      - account
  /api/v1/account/register_verify:
    post:
      consumes:
      - application/json
      description: 用户注册验证接口
      parameters:
      - description: register request body
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterVerifyReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dto.CommonResp'
            - properties:
                data:
                  $ref: '#/definitions/dto.RegisterVerifyResp'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.CommonResp'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.CommonResp'
      summary: 用户注册验证接口
      tags:
      - account
  /api/v1/account/reset_password:
    post:
      consumes:
      - application/json
      description: 用户修改密码接口
      parameters:
      - description: password reset request body
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/dto.ResetPasswordReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            set-cookie:
              description: cookie
              type: string
          schema:
            allOf:
            - $ref: '#/definitions/dto.CommonResp'
            - properties:
                data:
                  $ref: '#/definitions/dto.ResetPasswordResp'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.CommonResp'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.CommonResp'
      summary: 用户修改密码接口
      tags:
      - account
  /api/v1/account/update_password:
    post:
      consumes:
      - application/json
      description: 用户修改密码接口
      parameters:
      - description: password update request body
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/dto.PasswordUpdateReq'
      - description: csrf token
        in: header
        name: X-CSRF-TOKEN
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            set-cookie:
              description: cookie
              type: string
          schema:
            allOf:
            - $ref: '#/definitions/dto.CommonResp'
            - properties:
                data:
                  $ref: '#/definitions/dto.PasswordUpdateResp'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.CommonResp'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.CommonResp'
      summary: 用户修改密码接口
      tags:
      - account
  /api/v1/chat/stream:
    post:
      consumes:
      - application/json
      parameters:
      - description: request body
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/dto.ChatCreateReq'
      - description: csrf token
        in: header
        name: X-CSRF-TOKEN
        required: true
        type: string
      produces:
      - text/event-stream
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CommonResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.CommonResp'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.CommonResp'
      tags:
      - chat
  /api/v1/model/list:
    get:
      consumes:
      - application/json
      description: 获取模型列表
      parameters:
      - description: csrf token
        in: header
        name: X-CSRF-TOKEN
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            set-cookie:
              description: cookie
              type: string
          schema:
            allOf:
            - $ref: '#/definitions/dto.CommonResp'
            - properties:
                data:
                  $ref: '#/definitions/dto.ModelQueryResp'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.CommonResp'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.CommonResp'
      summary: 获取模型列表
      tags:
      - model
  /api/v1/ping:
    get:
      consumes:
      - application/json
      description: 测试 Description
      produces:
      - application/json
      responses: {}
      summary: 测试 Summary
schemes:
- http
swagger: "2.0"
